#! /bin/sh
sudo mkdir -p /home/<your gcp user>/ml-disk
sudo cp /etc/fstab /etc/fstab.backup
echo UUID=`sudo blkid -s UUID -o value /dev/sdb` /home/<your gcp user>/ml-disk ext4 discard,defaults,nofail 0 2 | sudo tee -a /etc/fstab
sudo chmod a+w /home/<your gcp user>/ml-disk